### ISSUE TITLE
Alright we need to talk...

### ISSUE THREAD

**Issue by Richard5656** [KrillNCrabs/The8#1]
![image](https://idratheranime.files.wordpress.com/2018/06/crying-luffy.jpg?w=382&h=214)

This project is within my top 10 projects ever this project even revealed one of my friends to be a snake man. Wow thank you for this. If I knew about this earlier I wouldn't have shaken his hand.

**Comment by KrillNCrabs** [comment]
I give you many tanks for your appreciation of my project

**Comment by Richard5656** [comment]
Make an update to this. I need to know if I want to use a spork or a spoon and a fork.

**Comment by KrillNCrabs** [comment]
I can answer this question for you. Just use a fooon

**Comment by Richard5656** [comment]
your rizz is great jus t like your answer

**Comment by Richard5656** [comment]
Reopened the issue
