### ISSUE TITLE
A wise man once said no arms no legs. Scales and tails it's a snake man. 

### ISSUE THREAD

**Issue by Richard5656** [KrillNCrabs/The8#3]
You're being accused of being a snake man. 

Is Krillin Crabs a snake man?

![snake arc issues](https://github.com/KrillNCrabs/The8/assets/80961838/e0f3b937-7533-4393-aff9-399a4f6b2f3d)

See I told you. Now face the wrath of my snake extermination flamethrower. 

![31411278](https://github.com/KrillNCrabs/The8/assets/80961838/2297e8c0-cf66-403a-ab46-b793b0dd0630)

**Comment by Richard5656** [comment]
The red on that mans face is not blood. It's tabasco

**Comment by Richard5656** [comment]
/summon @s KrillNCrabs's_friends

No targets matched your selector.

**Comment by Richard5656** [comment]
/summon ~ ~ ~ KrillNCrabs's_friends

Not targets matched your selector.

**Comment by Richard5656** [comment]
That's a real skull moment. You could say it's a bone joke. 
![R](https://github.com/KrillNCrabs/The8/assets/80961838/74cc8657-c280-44e4-a95d-ee86ceba000f)
YoHoHoHo

**Comment by Richard5656** [comment]
Your 8 ball got more screen time on my screen than shanks.

**Comment by Richard5656** [comment]
Fishy fever much

**Comment by KrillNCrabs** [comment]
https://docs.github.com/en/site-policy/github-terms/github-community-guidelines
